
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfName;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.icepdf.core.views.DocumentViewController;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author scott
 */
public class ProductEntry extends javax.swing.JFrame {

    /**
     * Creates new form ProductEntry
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    DefaultTableModel dm;
    public ProductEntry() {
        
        initComponents();
        conn=JavaConnect.ConnecrDb();
        setLocationRelativeTo(null);
        
        category();
      
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        sprice = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bprice = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Selling Price");

        jLabel2.setText("Category");

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel3.setText("Name");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setOpaque(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        sprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spriceKeyTyped(evt);
            }
        });

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        jLabel4.setText("Buying Price");

        bprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bpriceKeyTyped(evt);
            }
        });

        id.setText("...");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityKeyTyped(evt);
            }
        });

        jLabel7.setText("Quantity");

        jButton7.setText("View");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setText("Search");

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton10.setText("New");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon-1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton8)))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-icon-1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantity)
                            .addComponent(jComboBox1, 0, 160, Short.MAX_VALUE)
                            .addComponent(name)
                            .addComponent(bprice)
                            .addComponent(sprice)
                            .addComponent(jTextField1))
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(id))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(sprice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bprice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("PRODUCT  ENTRY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void column(){
        dm=(DefaultTableModel)jTable2.getModel();
        dm.addColumn("");
    }
    public void filter(String query){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(dm);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
      public void table1(){
        try{
            String sql="select ID,category,Name,Buy_Price as 'Buying Price',Sell_Price as'Selling Price',Quantity from Product";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
             pst.close();
           rs.close();
           
        }catch(Exception e){
        }
    }
        private void category(){
        try{
            String sql="select * from Category";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String cat=rs.getString("Cat_Name");
                             
                jComboBox1.addItem(cat);   
                
            }
            pst.close();
            rs.close();
        }catch(Exception e){
            
        }
        
        }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(name.getText().equals("")||bprice.getText().equals("")||sprice.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill all the fields to proceed");
            return;

        }
       
        try{
            int p=JOptionPane.showConfirmDialog(null, "Are you sure you wanna delete","Delete",JOptionPane.YES_NO_OPTION);
            if(p==0){
                String sql="delete from Product where ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, id.getText());
                pst.execute();
                JOptionPane.showMessageDialog(this, "Successfully deleted");
               
                name.setText("");
                bprice.setText("");
                sprice.setText("");
                 quantity.setText("");
                pst.close();
                rs.close();

            }
            table1();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        try{
            int row=jTable2.getSelectedRow();
            String tableclick=(jTable2.getModel().getValueAt(row,0).toString());
            String sql="select * from Product where ID='"+tableclick+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add=rs.getString("ID");
                id.setText(add);
                String add2=rs.getString("Name");
                name.setText(add2);
                String add3=rs.getString("Buy_Price");
                bprice.setText(add3);
                String add4=rs.getString("Sell_Price");
                sprice.setText(add4);
                String add5=rs.getString("Quantity");
                quantity.setText(add5);
                jComboBox1.setSelectedItem(jTable2.getValueAt(row, 1));

                pst.close();
                rs.close();

            }

        }catch(Exception e){
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void spriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spriceKeyTyped
        // TODO add your handling code here:
        if(sprice.getText().length()>=6){
            evt.consume();
        }
        if(!Character.isDigit(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_spriceKeyTyped

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:

        //if(Character.isDigit(evt.getKeyChar()))
       // evt.consume();
    }//GEN-LAST:event_nameKeyTyped

    public void updatestock(){
    
    
        try{
            String value=quantity.getText();
            String sql1="Select *  from Product where Name =?";
            
            pst=conn.prepareStatement(sql1);
            pst.setString(1,(String) name.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String a1=rs.getString("Quantity");
                int sum=Integer.parseInt(a1)+Integer. parseInt(value);
                String sum1=String.valueOf(sum);
                pst.close();
                rs.close();
                String value1=name.getText();
                String sql="update Product set Quantity='"+sum1+"' where Name='"+value1+"' ";
                pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
            pst.close();
            rs.close();
             
                 name.setText("");
                bprice.setText("");
                sprice.setText("");
                quantity.setText("");
           
            
                
            }
            
          
            
            

           

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        finally{
            try{
                pst.close();
                rs.close();
            }catch(Exception e){}
        }
    }
    public void update(){
    
    
         if(name.getText().equals("")||bprice.getText().equals("")||sprice.getText().equals("")){

            JOptionPane.showMessageDialog(this, "Please select the product to update");
            return;

        }
        String a=bprice.getText();
        String b=sprice.getText();
        
        int sum=Integer.parseInt(a);
        int sum1=Integer.parseInt(b);
   
        if(sum <=0){
            JOptionPane.showMessageDialog(this, "You cannot have 0 Buying Price ");
            return;

        }else if(sum1<=0){
            JOptionPane.showMessageDialog(this, "Cannot have 0 selling Price  ");
            return;
        }else if(sum >= sum1){
            JOptionPane.showMessageDialog(this, "Sellng Price cannot be lower than Buying price");
            return;
        }
        try{
            int p=JOptionPane.showConfirmDialog(null, "Are you sure wanna update","Update",JOptionPane.YES_NO_OPTION);
            if(p==0){
                String value=name.getText();
                String value1=bprice.getText();
                String value2=sprice.getText();

                String sql="update Product set Buy_Price='"+value1+"',Sell_Price='"+value2+"' where Name='"+value+"'  ";
                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Successfully updated");
                pst.close();
                rs.close();
            
              
            }
        }catch(Exception e){
            
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
       
        update();
        
        updatestock();
        table1();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpriceKeyTyped
        // TODO add your handling code here:
        if(bprice.getText().length()>=6){
            evt.consume();
        }
        if(!Character.isDigit(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_bpriceKeyTyped

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        name.setText("");
        bprice.setText("");
        sprice.setText("");
        quantity.setText("");
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       dispose();
       ProductCat pc=new ProductCat();
       pc.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try{
            String sql="Select * from Product where Name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
            String add=rs.getString("Quantity");
            quantity.setText(add);
            
            String add1=rs.getString("Category");
            jComboBox1.setSelectedItem(add1);
            
            String add3=rs.getString("ID");
                id.setText(add3);
                String add2=rs.getString("Name");
                name.setText(add2);
                String add6=rs.getString("Buy_Price");
                bprice.setText(add6);
                String add4=rs.getString("Sell_Price");
                sprice.setText(add4);
                String add5=rs.getString("Quantity");
                quantity.setText(add5);
                
               
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
        }
         
              try{
            String sql="Select * from Product where Category=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
            String add=rs.getString("Quantity");
            quantity.setText(add);
            
            String add1=rs.getString("Category");
         jComboBox1.setSelectedItem(add1);
            
            String add3=rs.getString("ID");
                id.setText(add3);
                String add2=rs.getString("Name");
                name.setText(add2);
                String add6=rs.getString("Buy_Price");
                bprice.setText(add6);
                String add4=rs.getString("Sell_Price");
                sprice.setText(add4);
                String add5=rs.getString("Quantity");
                quantity.setText(add5);
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
        }
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             try{
            String sql="Select * from Product where Name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
            String add=rs.getString("Quantity");
            quantity.setText(add);
            
            String add1=rs.getString("Category");
            jComboBox1.setSelectedItem(add1);
            
            String add3=rs.getString("ID");
                id.setText(add3);
                String add2=rs.getString("Name");
                name.setText(add2);
                String add6=rs.getString("Buy_Price");
                bprice.setText(add6);
                String add4=rs.getString("Sell_Price");
                sprice.setText(add4);
                String add5=rs.getString("Quantity");
                quantity.setText(add5);
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
        }
         
              try{
            String sql="Select * from Product where Category=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
            String add=rs.getString("Quantity");
            quantity.setText(add);
            
            String add1=rs.getString("Category");
         jComboBox1.setSelectedItem(add1);
            
            String add3=rs.getString("ID");
                id.setText(add3);
                String add2=rs.getString("Name");
                name.setText(add2);
                String add6=rs.getString("Buy_Price");
                bprice.setText(add6);
                String add4=rs.getString("Sell_Price");
                sprice.setText(add4);
                String add5=rs.getString("Quantity");
                quantity.setText(add5);
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
        }
            
        }
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyTyped
        // TODO add your handling code here:
          if(bprice.getText().length()>=6){
            evt.consume();
        }
        if(!Character.isDigit(evt.getKeyChar()))
        evt.consume();
   
    }//GEN-LAST:event_quantityKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       table1();
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String a=bprice.getText();
        String b=sprice.getText();

        int sum=Integer.parseInt(a);
        int sum1=Integer.parseInt(b);

        if(sum <=0){
            JOptionPane.showMessageDialog(this, "You cannot have 0 Buying Price ");
            return;

        }else if(sum1<=0){
            JOptionPane.showMessageDialog(this, "Cannot have 0 selling Price  ");
            return;
        }else if(sum >= sum1){
            JOptionPane.showMessageDialog(this, "Sellng Price cannot be lower than Buying price");
            return;
        }

        if(name.getText().equals("")||bprice.getText().equals("")||sprice.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill all the fields to proceed");
            return;

        }

        try{
            String sql="select * from Product where Name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, name.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "The product name already exist");
                return;
            }
            pst.close();
            rs.close();

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        try{
            String sql="insert into Product(Category,Name,Buy_Price,Sell_price,Quantity) Values(?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,(String)jComboBox1.getSelectedItem());
            pst.setString(2, name.getText());
            pst.setString(3, bprice.getText());
            pst.setString(4, sprice.getText());
            pst.setString(5, quantity.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Product Successfuly Saved");
            pst.close();
            rs.close();
               table1();
            name.setText("");
            bprice.setText("");
            sprice.setText("");
            quantity.setText("");

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="Select Category,Name,Buy_price,Sell_Price,Quantity from  Product ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
             Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Product.pdf"));
                document.open();
                 Calendar cal = new GregorianCalendar();
                int month = cal.get(Calendar.MONTH);
                int year = cal.get(Calendar.YEAR);
                int day = cal.get(Calendar.DAY_OF_MONTH);
                document.add(new Paragraph("                                                        Scott Technology "));
                document.add(new Paragraph("                                                    P.O. BOX 6 MOI'S BRIDGE"));
                document.add(new Paragraph("                                                EMAIL:scotttech@gmail.com"));

                document.add(new Paragraph(day + "-" + month + "-" + year));
                document.add(new Paragraph(new Date().toString()));
                document.add(new Paragraph("..................................."));
          
            PdfPTable table = new PdfPTable(5);
          
            table.addCell("Product Category");
             table.addCell("Product Name");
              table.addCell("Buy Price");
               table.addCell("Sell Price");
                table.addCell("Quantity");
           
            //
            
            while(rs.next()) {
              
               String data1 = rs.getString("Category");
               String data2 = rs.getString("Name");
               String data3 = rs.getString("Buy_price");
               String data4 = rs.getString("Sell_Price");
               String data5 = rs.getString("Quantity");
             
               
                table.addCell(data1);
                table.addCell(data2);
                table.addCell(data3);
                table.addCell(data4);
                table.addCell(data5);
                
                
               
                //
           } 
           document.add(table);
          //      document.add(new Paragraph("        ", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.BLUE)));
            document.close();

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        try{
            String path="C:\\Users\\Mureti Martin\\Documents\\NetBeansProjects\\Business Management System\\Product.pdf";
                SwingController controller=new SwingController();
                SwingViewBuilder factory=new SwingViewBuilder(controller);
                controller.setIsEmbeddedComponent(true);
                
                DocumentViewController viewController=controller.getDocumentViewController();
                JPanel viewerComponetPanel =factory.buildViewerPanel();
                ComponentKeyBinding.install(controller, viewerComponetPanel);
                controller.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));

                
                JFrame appframe=new JFrame();
                appframe.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                appframe.getContentPane().setLayout(new BorderLayout());
                appframe.getContentPane().add(viewerComponetPanel,BorderLayout.CENTER);
                appframe.getContentPane().add(factory.buildCompleteMenuBar(),BorderLayout.NORTH);
                appframe.setLocation(200,10);

                controller.setPageViewMode(0,false);
                controller.openDocument(path);
                appframe.pack();
                appframe.setVisible(true);
               rs.close();
               pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
       
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtatoo.plaf.smart.SmartLookAndFeel");
                }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bprice;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField sprice;
    // End of variables declaration//GEN-END:variables
}
