
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import org.icepdf.core.views.DocumentViewController;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mureti Martin
 */

public class ReportAll extends javax.swing.JFrame {

    /**
     * Creates new form ReportAll
     */
     Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public ReportAll() {
        super("Reports");
        initComponents();
        conn=JavaConnect.ConnecrDb();
        setLocationRelativeTo(null);
        category();
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Based of Product Category");

        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("SALES");

        jButton3.setText("Generate  Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel3))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void date(){
        Date date=new  Date();
        jDateChooser5.setDate(date);
        jDateChooser6.setDate(date);
        
             jDateChooser5.setSelectableDateRange(null, date);
             jDateChooser6.setSelectableDateRange(null, date);
  
    }
     
    private void category(){
        try{
            String sql="select * from Product";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String cat=rs.getString("Category");
                             
                jComboBox1.addItem(cat);   
                
            }
            pst.close();
            rs.close();
        }catch(Exception e){
            
        }
      }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String date1=((JTextField)jDateChooser5.getDateEditor().getUiComponent()).getText();
        String date2=((JTextField)jDateChooser6.getDateEditor().getUiComponent()).getText();
        try{
            String sql="Select Code,Name,price from Sales where Date between '"+date1+"' and '"+date2+"'  ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Document document =new Document();
            PdfWriter.getInstance(document, new FileOutputStream("ViewSales.pdf"));
            document.open();
            
             
                document.add(new Paragraph("                                                        Scott-tech Technology "));
                document.add(new Paragraph("                                                    P.O. BOX 6000 Nairobi"));
                document.add(new Paragraph("                                                EMAIL:scotttech@gmail.com"));

              
                document.add(new Paragraph(new Date().toString()));
              
                document.add(new Paragraph(""));
          
         //
            PdfPTable table = new PdfPTable(3);
           
            table.addCell("Code");
            table.addCell("Name");
            table.addCell("Price");
           
            //
            
            while(rs.next()) {
                
                String data1 = rs.getString("Code");
                String  data2 = rs.getString("Name");
                String data3 = rs.getString("Price");
                
               
               
                table.addCell(data1);
                table.addCell(data2);
                table.addCell(data3);
                
               
               
                //
           } 
           document.add(table);
          //      document.add(new Paragraph("        ", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.BLUE)));
            document.close();

                    
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        
       try{
            String path="C:\\Users\\Mureti Martin\\Documents\\NetBeansProjects\\Business Management System\\ViewSales.pdf";
                SwingController controller=new SwingController();
                SwingViewBuilder factory=new SwingViewBuilder(controller);
                controller.setIsEmbeddedComponent(true);
                
                DocumentViewController viewController=controller.getDocumentViewController();
                JPanel viewerComponetPanel =factory.buildViewerPanel();
                ComponentKeyBinding.install(controller, viewerComponetPanel);
                controller.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));

                
                JFrame appframe=new JFrame();
                appframe.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                appframe.getContentPane().setLayout(new BorderLayout());
                appframe.getContentPane().add(viewerComponetPanel,BorderLayout.CENTER);
                appframe.getContentPane().add(factory.buildCompleteMenuBar(),BorderLayout.NORTH);
                appframe.setLocation(200,10);

                controller.setPageViewMode(0,false);
                controller.openDocument(path);
                appframe.pack();
                appframe.setVisible(true);
                rs.close();
                pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
             String date=(String)jComboBox1.getSelectedItem();
       
           String sql="Select * from Product where Category=?  ";
            pst=conn.prepareStatement(sql);
            pst.setString(1, date);
           
            rs=pst.executeQuery();
            Document document =new Document();
            PdfWriter.getInstance(document, new FileOutputStream("AccordingClass.pdf"));
            document.open();
            
             
                document.add(new Paragraph("                                                        Scott Tech Technology "));
                document.add(new Paragraph("                                                    P.O. BOX 6000 Nairobi"));
                document.add(new Paragraph("                                                EMAIL:scott@gmail.com"));

              
                document.add(new Paragraph(new java.util.Date().toString()));
              
                document.add(new Paragraph(date));
               
             
                
          
         //
            PdfPTable table = new PdfPTable(4);
           
            table.addCell("Product Name");
            table.addCell("Buy Price");
            table.addCell("Sell price");
            table.addCell("Quantity");
           
            
          
            
           
            //
            
            while(rs.next()) {
                
                String data1 = rs.getString("Name");
                String  data2 = rs.getString("Buy_Price");
                String data3 = rs.getString("Sell_Price");
                String data4 = rs.getString("Quantity");
               
                
                
                
               
               
                table.addCell(data1);
                table.addCell(data2);
                table.addCell(data3);
                 table.addCell(data4);
               
               
                
               
               
                //
           } 
           document.add(table);
          //      document.add(new Paragraph("        ", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.BLUE)));
            document.close();

                    
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        try{
            String path="C:\\Users\\Mureti Martin\\Documents\\NetBeansProjects\\Business Management System\\AccordingClass.pdf";
                SwingController controller=new SwingController();
                SwingViewBuilder factory=new SwingViewBuilder(controller);
                controller.setIsEmbeddedComponent(true);
                
                DocumentViewController viewController=controller.getDocumentViewController();
                JPanel viewerComponetPanel =factory.buildViewerPanel();
                ComponentKeyBinding.install(controller, viewerComponetPanel);
                controller.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));

                
                JFrame appframe=new JFrame();
                appframe.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                appframe.getContentPane().setLayout(new BorderLayout());
                appframe.getContentPane().add(viewerComponetPanel,BorderLayout.CENTER);
                appframe.getContentPane().add(factory.buildCompleteMenuBar(),BorderLayout.NORTH);
                appframe.setLocation(200,10);

                controller.setPageViewMode(0,false);
                controller.openDocument(path);
                appframe.pack();
                appframe.setVisible(true);
                rs.close();
                pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                     /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtatoo.plaf.smart.SmartLookAndFeel");
                }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
