
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.text.*;
import java.awt.print.*;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.icepdf.core.views.DocumentViewController;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author scott
 */
public class Saless extends javax.swing.JFrame {

    /**
     *
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    DefaultTableModel dm1;
    double num1;
    double num2;
    double result;
    String operations;
    double firstnum;
    double secondnum;
    double result1;
    String operations1;
    DefaultTableModel dm;

    public Saless() {
        super("Make Sales");
        initComponents();
        conn = JavaConnect.ConnecrDb();
        setLocationRelativeTo(null);
        random();
        product();

        Date();

        jDateChooser2.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        display = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ball = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        quantity = new javax.swing.JTextField();
        qrm = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vat = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Total  Amount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Price");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Sales Code");

        display.setEditable(false);

        code.setEditable(false);

        price.setEditable(false);
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Product Name");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButton1.setText("View Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Add ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(code))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 121, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ball, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(display)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(ball, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE))
        );

        id.setText("...");

        id1.setText("...");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Print Receipt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton8))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(29, 29, 29)
                .addComponent(jButton8)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        quantity.setEditable(false);

        qrm.setEditable(false);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Quantity Remaining");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Quantity Available");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Vat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qrm)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(vat)))
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTextPane1.setEditable(false);
        jScrollPane3.setViewportView(jTextPane1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("SALES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(id1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(id)
                        .addGap(133, 133, 133)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id1)
                            .addComponent(id))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Date() {
        Date date = new Date();
        jDateChooser2.setDate(date);
    }

    

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//       
//receipt();

quantity.setText("");
jTextField1.setText("");
price.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    public void random() {
        Random ra = new Random();
        code.setText("" + ra.nextInt(1000 + 0));
    }

    public void table() {
        try {
            String sql = "select * from Sales";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //     jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }

    public void product() {
        try {
            String sql = "select * from Product ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String add = rs.getString("Name");
                jComboBox1.addItem(add);
            }
            pst.close();
            rs.close();
        } catch (Exception e) {
        }

    }

    public void stock() {
        try {
            String sql = "select * from Product  where Name=?";
            String a1 = (String) jComboBox1.getSelectedItem();
            pst = conn.prepareStatement(sql);
            pst.setString(1, a1);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add = rs.getString("Quantity");
                quantity.setText(add);
            }
            pst.close();
            rs.close();
        } catch (Exception e) {
        }

    }

    public void quantity() {
        try {
            String a1 = quantity.getText();
            String a2 = jTextField1.getText();
            int diff = Integer.parseInt(a1) - Integer.parseInt(a2);
            String difference = String.valueOf(diff);
            qrm.setText(difference);
        } catch (Exception e) {
        }
    }

    public void newquantity() {
        try {

            String value = qrm.getText();
            String value1 = (String) jComboBox1.getSelectedItem();
            String sql = "update Product set Quantity='" + value + "' where Name='" + value1 + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            rs.close();
            //quantity.setText("");
            //qrm.setText("");
            //jTextField1.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void save1() {
        try {
            if (quantity.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Empty Fields");
                return;
            }
            String a1 = quantity.getText();
            String a2 = qrm.getText();
            String a3 = jTextField1.getText();
            int sum3 = Integer.parseInt(a3);

            int sum1 = Integer.parseInt(a2);
            int sum = Integer.parseInt(a1);
            if (sum3 < 0) {
                JOptionPane.showMessageDialog(this, "You cant have negatvie  quantity");
                return;
            }
            if (sum < 0 || sum1 < 0) {
                JOptionPane.showMessageDialog(this, "Cannot sell 0 quantity");
                return;
            } else if (jTextField1.getText().equals("0")) {
                JOptionPane.showMessageDialog(this, "Cannot sell 0 quantity");
                return;
            }

            String sql = "insert into Sales(Code,Name,Price,balance,Date,Quantity) Values(?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, code.getText());
            pst.setString(2, (String) jComboBox1.getSelectedItem());
            pst.setString(3, display.getText());
            pst.setString(4, ball.getText());
            pst.setString(5, ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText());
            pst.setString(6, jTextField1.getText());

            

            pst.execute();
            JOptionPane.showMessageDialog(this, "saved successfully");
            pst.close();
            rs.close();
            newquantity();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void receipt() {
        try {
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            PageFormat pgformat = printerJob.defaultPage();
            Paper paper = new Paper();
            double lines = 0;
            paper.setSize(180.0, (double) (paper.getHeight() + lines * 10.0));
            int margin = 0;
            paper.setImageableArea(margin, margin, paper.getWidth() - margin * 2, paper.getHeight() - margin * 2);
            pgformat.setPaper(paper);
            pgformat.setOrientation(PageFormat.PORTRAIT);
            printerJob.setPrintable(jTextPane1.getPrintable(null, null), pgformat);
            printerJob.print();

        } catch (PrinterException ex) {
            Logger.getLogger(Saless.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
//        double value = Double.parseDouble(ballance.getText());
//        double value1 = Double.parseDouble(total.getText());
//
//        if (value < value1) {
//            JOptionPane.showMessageDialog(this, "Amount Paid cant be less that the price of the product");
//            return;
//        }
//
            try{
               if(display.getText().equals("")){
               
                   JOptionPane.showMessageDialog(this, "Cant print");
                   return;
               }
            jTextPane1.print();
        }catch(Exception e){}

       
        String a1 = quantity.getText();
        String a2 = qrm.getText();
        String a3 = jTextField1.getText();
        int sum3 = Integer.parseInt(a3);
    
        int sum1 = Integer.parseInt(a2);
        int sum = Integer.parseInt(a1);
        if (sum3 < 0) {
            JOptionPane.showMessageDialog(this, "You cant have negatvie  quantity");
            return;
        }
        if (sum < 0 || sum1 < 0) {
            JOptionPane.showMessageDialog(this, "Cannot sell 0 quantity");
            return;
        } else if (jTextField1.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Cannot sell 0 quantity");
            return;
        }

        //save1();
        

        /* String add=quantity.getText();
        String add1=qrm.getText();
        int sum=Integer.parseInt(add);
        int sum1=Integer.parseInt(add1);

        if(sum < 0||sum1 < 0){
            JOptionPane.showMessageDialog(this, "Cannnot sell 0 quantity");
            return;
        }else if(jTextField1.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "Cannot sell 0 quantity");
            return;
        }*/
        
               newquantity();
        code.setText("");
        price.setText("");
//        total.setText("");
        ball.setText("");
//        ballance.setText("");
        jTextField1.setText("");
        random();
        display.setText("");
        quantity.setText("");
        qrm.setText("");
//        vat.setText("");


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (jTextField1.getText().length() >= 2) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:

        String a1 = quantity.getText();
        String a2 = jTextField1.getText();
        int sum = Integer.parseInt(a2);
        int value=Integer.parseInt(a1);
        if (sum <= 0) {
            JOptionPane.showMessageDialog(this, "you cant have negative values");
            return;
        }if(sum>value){
        
            JOptionPane.showMessageDialog(this, "Cant sell more than remmaining quantuty");
            return;
        }
        int sum1 = Integer.parseInt(a1) - Integer.parseInt(a2);
        String sum2 = String.valueOf(sum1);
        qrm.setText(sum2);

        String add = price.getText();
        String add1 = jTextField1.getText();
        String add2=vat.getText();

        double prouct = Double.parseDouble(add1) * Double.parseDouble(add);
        String product1 = String.valueOf(prouct);
        display.setText(product1);

       String pric = price.getText();
       String quant = jTextField1.getText();
      double tax = Integer.parseInt(pric) * Integer.parseInt(quant) * 0.05;
       String vattax = String.valueOf(tax);
      vat.setText(vattax);


    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Select Code,Name,Price from Sales ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Sales.pdf"));
            document.open();

            Calendar cal = new GregorianCalendar();
            int month = cal.get(Calendar.MONTH);
            int year = cal.get(Calendar.YEAR);
            int day = cal.get(Calendar.DAY_OF_MONTH);
            document.add(new Paragraph("                                                         Technology Company "));
            document.add(new Paragraph("                                                    P.O. BOX 2000 Nairobi"));
            document.add(new Paragraph("                                                EMAIL:tech@gmail.com"));

            document.add(new Paragraph(day + "-" + month + "-" + year));
            document.add(new Paragraph(new Date().toString()));

            document.add(new Paragraph("..................................."));

            PdfPTable table = new PdfPTable(3);

            table.addCell("Code");
            table.addCell("Product Name");
            table.addCell("Price");

            //
            while (rs.next()) {

                String data1 = rs.getString("Code");
                String data2 = rs.getString("Name");
                String data3 = rs.getString("Price");

                table.addCell(data1);
                table.addCell(data2);
                table.addCell(data3);

                //
            }
            document.add(table);
            //      document.add(new Paragraph("        ", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.BLUE)));
            document.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        try {
            String path = "C:\\Users\\Mureti Martin\\Documents\\NetBeansProjects\\Business Management System\\Sales.pdf";
            SwingController controller = new SwingController();
            SwingViewBuilder factory = new SwingViewBuilder(controller);
            controller.setIsEmbeddedComponent(true);

            DocumentViewController viewController = controller.getDocumentViewController();
            JPanel viewerComponetPanel = factory.buildViewerPanel();
            ComponentKeyBinding.install(controller, viewerComponetPanel);
            controller.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));

            JFrame appframe = new JFrame();
            appframe.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            appframe.getContentPane().setLayout(new BorderLayout());
            appframe.getContentPane().add(viewerComponetPanel, BorderLayout.CENTER);
            appframe.getContentPane().add(factory.buildCompleteMenuBar(), BorderLayout.NORTH);
            appframe.setLocation(200, 10);

            controller.setPageViewMode(0, false);
            controller.openDocument(path);
            appframe.pack();
            appframe.setVisible(true);
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String answer;
//        num2=Double.parseDouble(display.getText());
//        if(operations=="+")
//        {
//            result=num1+num2;
//            answer=String.format("%.0f", result);
//            display.setText(answer);
//            total.setText(answer);
//        }else{
//            total.setText(display.getText());
//        }

//        String add = vat.getText();
//        String add1 = display.getText();
//
//        double sum =  Double.parseDouble(add)+Double.parseDouble(add1);
//        String sum1 = String.valueOf(sum);
//        display.setText(sum1);
//        
        
       
        
       
       try {

            String ln1 = String.format("%-15s %5s %10s\n", "------", "----", "-----");

            String ln2 = String.format("%-15s %5s %10.2f\n\n", "Total", totq, totals);

            String tt = jTextPane1.getText();

            jTextPane1.setText(tt + ln1 + ln2);

           
          
        } catch (NullPointerException e) {

            JOptionPane.showMessageDialog(null, e);



        }

       // total();
        //quantity();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void total() {

        display.setText("");
    }
    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            String value1 = (String) jComboBox1.getSelectedItem();
            String sql = "select * from Product where Name=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, value1);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add = rs.getString("Sell_price");

                price.setText(add);

                String add1 = rs.getString("Quantity");
                quantity.setText(add1);

                String add2 = rs.getString("Name");
                name.setText(add2);

            }

            pst.close();
            rs.close();
        } catch (Exception e) {
        }
        stock();
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible


        double totals = 0;

    int totq = 0;

    double totmoney = 0;

    double tmoney = 0;

    public void additem() {
        if(qrm.getText().equals("")||jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty Fields");
            return;
        
        }

        try {

            String item =name.getText();

            String qty = jTextField1.getText();

            int qtyy = Integer.parseInt(qty);

            String cst = display.getText();

            double cost = Double.parseDouble(cst);

            String line = String.format("%-15s %5d %10.2f\n", item, qtyy, cost);

            totals += cost;

            totq += qtyy;

            String Rtp = jTextPane1.getText();

            jTextPane1.setText(Rtp + line);
          
            
        } catch (NullPointerException e) {

            JOptionPane.showMessageDialog(this, "Empty Fields", "Message", JOptionPane.ERROR_MESSAGE);
            return;

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Empty Fields", "Message", JOptionPane.ERROR_MESSAGE);
            return;

        }
      
        
    }
    public void pullup() {

        String dates = new SimpleDateFormat("EEEE   dd-MM-yyyy     HH:mm:ss\n\n").format(new Date());

        String s0 = String.format("TECHNOLOGY COMPANY\n");

        String s01 = String.format(dates);

        String s = String.format("%-15s %5s %10s\n", "Item", "Qty", "Amount");

        String s1 = String.format("%-15s %5s %10s\n", "------", "-----", "------");

        String output = s0 + s01 + s + s1;

        jTextPane1.setText(output);

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
          pullup();
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void reset(){
    
        
quantity.setText("");
jTextField1.setText("");
price.setText("");
qrm.setText("");
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String add=vat.getText();
        String add1=display.getText();
        
         double prouct = Double.parseDouble(add1) + Double.parseDouble(add);
        String product1 = String.valueOf(prouct);
        display.setText(product1);
         if(qrm.getText().equals("")||jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty Fields");
            return;
        
        }
        

        additem();
       
       
       newquantity();
        save1();
      
      reset();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_priceKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtatoo.plaf.smart.SmartLookAndFeel");
                }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saless().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ball;
    private javax.swing.JTextField code;
    private javax.swing.JTextField display;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qrm;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField vat;
    // End of variables declaration//GEN-END:variables
}
